name: CI Packages
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Login to Octopus Deploy
      uses: OctopusDeploy/login@v1.0.1
      with:
         server: "https://octopus-workshop.octopus.app/"
         service_account_id: "798ca80b-de7b-4cc2-91ba-b334d0e202dd"

    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: |
        dotnet restore ./OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj
        dotnet restore ./OctopusSamples.OctoPetShop.ProductService/OctopusSamples.OctoPetShop.ProductService.csproj
        dotnet restore ./OctopusSamples.OctoPetShop.Database/OctopusSamples.OctoPetShop.Database.csproj
        dotnet restore ./OctopusSamples.OctoPetShop.ShoppingCartService/OctopusSamples.OctoPetShop.ShoppingCartService.csproj

    - name: Build
      run: |
        dotnet build ./OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj --configuration Release --no-restore
        dotnet build ./OctopusSamples.OctoPetShop.ProductService/OctopusSamples.OctoPetShop.ProductService.csproj --configuration Release --no-restore
        dotnet build ./OctopusSamples.OctoPetShop.ShoppingCartService/OctopusSamples.OctoPetShop.ShoppingCartService.csproj --configuration Release --no-restore

    - name: Publish
      run: |
        dotnet publish OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj --configuration Release --no-restore --output ${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.Web
        dotnet publish OctopusSamples.OctoPetShop.ProductService/OctopusSamples.OctoPetShop.ProductService.csproj --configuration Release --no-restore --output ${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.ProductService
        dotnet publish OctopusSamples.OctoPetShop.Database/OctopusSamples.OctoPetShop.Database.csproj --configuration Release --no-restore --output ${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.Database
        dotnet publish OctopusSamples.OctoPetShop.ShoppingCartService/OctopusSamples.OctoPetShop.ShoppingCartService.csproj --configuration Release --no-restore --output ${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.ShoppingCartService

    - name: Create Web NuGet package 🐙
      uses: OctopusDeploy/create-nuget-package-action@v3
      with:
        package_id: 'OctoPetShop.Web'
        version: ${{ env.PACKAGE_VERSION }}
        base_path: '${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.Web'
        output_folder: '${{ github.workspace }}/artifacts'
        nuspec_description: 'OctoPetShop.Web package'
        nuspec_authors: 'OctoPetShop Team'
        files: |
          **/*

    - name: Create Database NuGet package 🐙
      uses: OctopusDeploy/create-nuget-package-action@v3
      with:
        package_id: 'OctoPetShop.Database'
        version: ${{ env.PACKAGE_VERSION }}
        base_path: '${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.Database'
        output_folder: '${{ github.workspace }}/artifacts'
        nuspec_description: 'OctoPetShop.Database package'
        nuspec_authors: 'OctoPetShop Team'
        files: |
          **/*


    - name: Create ShoppingCartService NuGet package 🐙
      uses: OctopusDeploy/create-nuget-package-action@v3
      with:
        package_id: 'OctoPetShop.ShoppingCartService'
        version: ${{ env.PACKAGE_VERSION }}
        base_path: '${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.ShoppingCartService'
        output_folder: '${{ github.workspace }}/artifacts'
        nuspec_description: 'OctoPetShop.ShoppingCartService package'
        nuspec_authors: 'OctoPetShop Team'
        files: |
          **/*

    - name: Create Product Service NuGet package 🐙
      uses: OctopusDeploy/create-nuget-package-action@v3
      with:
        package_id: 'OctoPetShop.ProductService'
        version: ${{ env.PACKAGE_VERSION }}
        base_path: '${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.ProductService'
        output_folder: '${{ github.workspace }}/artifacts'
        nuspec_description: 'OctoPetShop.ProductService package'
        nuspec_authors: 'OctoPetShop Team'
        files: |
          **/*

    - name: Push Build Information to Octopus
      uses: OctopusDeploy/push-build-information-action@v3
      with:
          space: Platform
          packages: | 
            OctoPetShop.Web
            OctoPetShop.Database.flyway
            OctoPetShop.ProductService
            OctoPetShop.ShoppingCartService
          version: ${{ env.PACKAGE_VERSION }}

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v2
      with:
        version: '2.73.0'

    - name: Configure JFrog CLI
      run: |
        jf config add --url="${{ secrets.ARTIFACTORY_URL }}" --user="${{ secrets.ARTIFACTORY_USERNAME }}" --password="${{ secrets.ARTIFACTORY_PASSWORD }}" --interactive=false

    - name: Upload packages to Artifactory
      run: |
       jfrog rt u "${{ github.workspace }}/artifacts/*.nupkg" "demo-workshop-octopetshop-nuget/" --build-name="OctoPetShop" --build-number="${{ env.PACKAGE_VERSION }}"

