name: .NET Core 

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore ./OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj

    - name: Build
      run: dotnet build ./OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj --configuration Release --no-restore --output ${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.Web
      

    - name: Create Zip package 🐙
      uses: OctopusDeploy/create-zip-package-action@v3
      with:
        package_id: 'OctoPetShop.Web'
        version: ${{ env.PACKAGE_VERSION }}
        base_path: '${{ github.workspace }}/artifacts/OctopusSamples.OctoPetShop.Web'
        output_folder: '${{ github.workspace }}/artifacts'
        files: |
          **/*
