name: .NET Core 

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore ./OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj

    - name: Build
      run: dotnet build ./OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.Web"

    - name: Create NuGet Package
      run: |
        dotnet pack ./OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj --configuration Release --output "$GITHUB_WORKSPACE/artifacts" /p:PackageVersion=${{ env.PACKAGE_VERSION }}

    - name: Install NuGet CLI
      run: |
          curl -sSL https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o nuget.exe
      
    - name: Upload NuGet Package to Artifactory
      run: |
          ./nuget.exe sources Add -Name Artifactory -Source https://artifactory.octopussamples.com/artifactory/api/nuget/demo-adam-octopetshop --username ${{ secrets.ARTIFACTORY_USERNAME }} --password ${{ secrets.ARTIFACTORY_PASSWORD }}
          ./nuget.exe setapikey ${{secrets.ARTIFACTORY_USERNAME}}:${{ secrets.ARTIFACTORY_PASSWORD }} -source Artifactory
          